### ISSUE TITLE
Support for AC0650

### ISSUE THREAD

**Issue by williamgeurts** [kongo09/philips-airpurifier-coap#117]
Hi,
I have an AC0650/10, I use it with the Philips Air+ app on my iPhone. Until know there is no HomeAssistant support. If I try to get the raw data I get a connection refused message. 
WiFi firmware 1.6.0
Apparaat firmware 0.1.9

can you help or advise me?

**Comment by kongo09** [comment]
The device looks very similar to the 800 series, which is supported. However, if you don't get any raw data from the device, it will not work. Maybe this doesn't support encrypted CoAP. There are other integrations that can also use non-encrypted CoAP protocol, maybe that works?

I'll close this issue here, but let me know if you manage to extract some data and we can reopen and take a look.

**Comment by CsabaVK** [comment]
Is there any solution here? either non CoAP or any other way?

Im trying to connect the same device, 600 series

**Comment by williamgeurts** [comment]
No succes here. Sorry

**Comment by marcopaggioro** [comment]
I would also like to integrate it but the integration doesn't work.

**Comment by kongo09** [comment]
Sorry, the integration only supports encrypted CoAP. There are models that use unencrypted CoAP and another protocol, but I never spent the time to investigate the necessary changes more deeply. Ideally, someone with access to such a device can provide a pull request.

**Comment by marcopaggioro** [comment]
@kongo09 I have no idea how I can help otherwise I would gladly do it. Having a developer background is there any chance I can help with some tutorials?
