### ISSUE TITLE
Wrong indication of fan speed

### ISSUE THREAD

**Issue by lachezar-gizdov** [kongo09/philips-airpurifier-coap#194]
I don't know if this is a bug, or it's just the way it is with Philips Air Purifiers.
![image](https://github.com/user-attachments/assets/eeb4fc9f-bd09-4e9f-8109-c9c453e7cc7d)

When on Auto preset, the selected fan speed appears to be Off, but it's definitely not Off 😄

**Comment by kongo09** [comment]
In my view it is a problem of the HA card. If you have more speed settings so that it switches to percentages, it just goes grey when auto is selected:

![image](https://github.com/user-attachments/assets/34c12b8d-e9f2-40df-89bd-0345e554c3ac)

Grey probably also means off, but it looks less irritating. I'm not really sure how to fix this. I could put auto as a speed setting into the list of speeds, but that's also confusing, especially if percentages are shown. Any good idea is welcome.
