### ISSUE TITLE
[AC2729] Missing select entities for Speed/Modes

### ISSUE THREAD

**Issue by kkosyl** [kongo09/philips-airpurifier-coap#49]
Hi @kongo09,

I have Philips AC2729 and the integration works very well which is awesome. 

I have an issue with select entities for speed/modes though. I can see those presets in code but not in HA. Should those appear in HA as entites? (I have select for purification and purification with humidifier).

Greetings

**_EDIT:_**
I guess I found it. It looks like I would have to make buttons to call each mode, am I right? 
I thought I would get select entity as for the others - function/humidity. It was not entirely clear for me at the first place.

**Comment by kongo09** [comment]
They're not separate select entities because they're part of the HA fan model. If you select the fan entity and check the info section, you'll see all your options as slider and as drop-down:

![image](https://user-images.githubusercontent.com/640121/192135520-b84e508c-ac40-41e0-9470-592a67a0a406.png)

This is not a bug but the way fan operates.
