### ISSUE TITLE
Broken in new home-assistant version

### ISSUE THREAD

**Issue by dennisbrouwer91** [kongo09/philips-airpurifier-coap#50]
Hi,

In Home-Assistant 2022.11.0 the integration now errors with this : 
`Config entry 'AC1214 slaapkamer' for philips_airpurifier_coap integration not ready yet: Can't instantiate abstract class UDP6EndpointAddress with abstract method blockwise_key; Retrying in background`

Any idea what might be going wrong?

**Comment by kongo09** [comment]
I haven't upgraded yet, so let me try...

**Comment by dennisbrouwer91** [comment]
After multiple restarts of Home-Assistant is was suddenly fixed here, pretty strange!

**Comment by kongo09** [comment]
I did the upgrade and it works for me out of the box.

**Comment by dennisbrouwer91** [comment]
It indeed works, but sometimes the integration crashes with the error as shown in the initial message. It happens at least a couple of times per week, maybe good to double check the error on your side whenever possible?

**Comment by kongo09** [comment]
Thanks for sharing the observations. I'll keep an eye on this.

**Comment by XtrordinarY** [comment]
I have the same problem as @dennisbrouwer91 with the same error message but with a different model. It sometimes works after a few restarts but more often it doesn't than it does.

![image](https://user-images.githubusercontent.com/58817407/203272501-ba9eefd5-8159-45e4-a7ba-f3e66e2765af.png)

**Comment by dennisbrouwer91** [comment]
It feels like it has something to do with IPv6, because of the "UDP6" address error.

**Comment by rkrkrk0987** [comment]
nothing to do with ipv6, i already consulted https://github.com/chrysn/aiocoap/issues/295 and even checked and it doesn't work with ipv4 neither....
in my case it has correlation with wifi and ethernet (i can connect to it from any wifi device, but can't from any device connected to wifi router using ethernet) ... can't explain why

**Comment by kongo09** [comment]
Could it be that the CoAP messages are not routed properly? Maybe you are on a different subnet or they don't pass your router / switch but on the same WiFi access point you can see them?

**Comment by joe-sydney** [comment]
This may or may not be related, but since upgrading to 2022.11.x, I've been having intermittent errors and reverting back to 2022.10.x fixed it. Note that I am using the older philips_airpurifier_coap integration (where I found a way of recovering the entities by getting the air purifiers reconnected, and this has been working for a long time reliably now).

I opened an issue with aiocoap here:
https://github.com/chrysn/aiocoap/issues/296#issue-1475354194

**Comment by kongo09** [comment]
Thanks for letting us know!

How do you recover the entities?

**Comment by joe-sydney** [comment]
> Thanks for letting us know!
> 
> How do you recover the entities?

Since I use node-red for automation anyway, I use it to detect if the fan entity has disappeared or gone into unavailable/unknown state, and this triggers CLI commands to turn it on, pause, off, pause off (if the last state was off) and off, pause, on, pause, on (if last state was on)... This sequence was mainly from trial and error resulting in both of the 2 purifiers working consistently for perhaps more than 6 months now, without needing to touch HA or reset the integration...

The main downside is that each command results in a sound from the air purifier, but it doesn't happen often, and I don't do the checks when people are sleeping at night.

I guess this could be built into the integration too.

cheers
Joe

**Comment by kongo09** [comment]
You are telling me, this sequence brings the device back to live? That's crazy!

So in theory, this should be possible in HA as well? What criteria do you use to detect it is unavailable? And what CLI are you using?

**Comment by joe-sydney** [comment]
I just use the aioairctrl linux commands:
/usr/local/bin/aioairctrl -H purifier-IP set pwr=1 for on
/usr/local/bin/aioairctrl -H purifier-IP set pwr=0 for off

In node-red, I can use the "get-entities" node which returns 1 if that fan entity exists, and any other result, I assume the entity has disappeared (this is the first criteria). So this works when the integration starts up as well. I don't know if you can use HA to detect whether an entity exists (never tried). 

The second criteria is if the entity is not either On or Off (some other state)... 

Based on above two criteria, I then fire off the aioairctrl commands (with a 5 second pause between them). 

Within the integration itself, I presume you may be able to do something like that too? It should know whether the entity exists, and/or what state they are? I used to code in C, python is too much trouble for me :)

To test it out, next time the entities go into some bad state, perhaps you can try the CLI commands manually to validate the purifiers get connected again. At least it has worked for me....

**Comment by kongo09** [comment]
Thanks for this insight.

**Comment by joe-sydney** [comment]
No worries, hope it works for you. Using this method, the only time I had to touch HA was to upgrade it, and in this case, I was alerted to the intermittent issues with 2022.11.x because I heard the sounds made by the air purifiers quite frequently (due to the commands being sent to it each time node-red found an issue with the entity,

**Comment by joe-sydney** [comment]
Back to the issue now ... :) I suspect I am having issues after aiocoap updated to 0.4.5. However, since this was released 13 days ago, it wouldn't be the same issue as @dennisbrouwer91 which was reported earlier than that. In any case, since I am using an earlier integration, it may depend on whether the same issue is inherited by @kongo09 's fork. 

I am reverting to older releases of aiocoap and will keep monitoring to see if the issue goes away.

**Comment by kongo09** [comment]
My Home Assistant integration uses aioairctrl 0.2.3 and that uses aiocoap 0.4.3

**Comment by kongo09** [comment]
> I just use the aioairctrl linux commands: /usr/local/bin/aioairctrl -H purifier-IP set pwr=1 for on /usr/local/bin/aioairctrl -H purifier-IP set pwr=0 for off
> 
> In node-red, I can use the "get-entities" node which returns 1 if that fan entity exists, and any other result, I assume the entity has disappeared (this is the first criteria). So this works when the integration starts up as well. I don't know if you can use HA to detect whether an entity exists (never tried).
> 
> The second criteria is if the entity is not either On or Off (some other state)...
> 
> Based on above two criteria, I then fire off the aioairctrl commands (with a 5 second pause between them).
> 
> Within the integration itself, I presume you may be able to do something like that too? It should know whether the entity exists, and/or what state they are? I used to code in C, python is too much trouble for me :)
> 
> To test it out, next time the entities go into some bad state, perhaps you can try the CLI commands manually to validate the purifiers get connected again. At least it has worked for me....

This trick didn't work for me. Just tried...

**Comment by joe-sydney** [comment]
> This trick didn't work for me. Just tried...

I do remember trying your integration as it has really cool features but ended up reverting to the older integration. I can't remember exactly why but it could have been not being able to get the purifiers reconnected using the trick.

**Comment by kongo09** [comment]
If you ever figure out what it is, let me know. Happy to stick it in.

I've also just done a new beta with `aiocoap` 0.4.5 named `v0.11.0-aiocoap`. Not sure if this makes things better or worse.

**Comment by kongo09** [comment]
For me, stability has improved with the latest release. Please let me know if you still see the problem described above. If I don't hear anything, I'll close the issue.

**Comment by XtrordinarY** [comment]
Yeah the connection is way more stable now. I haven't noticed a drop in connection the past few days.

**Comment by dennisbrouwer91** [comment]
Also on my end it's way more stable, thanks so much!

**Comment by kongo09** [comment]
Thanks for the feedback. I'll close this issue now. For new problems, please start a new issue.
