### ISSUE TITLE
Not able to connect HA with AC2889/10

### ISSUE THREAD

**Issue by Obicom** [kongo09/philips-airpurifier-coap#79]
I connected the AC2889/10 with my Wifi successfully. Then I tried to add the integration with the IP address. After some seconds I got always "Timeout, cannot connect to device". Tried it several time. No success. Any hint or idea? (The Air+ app is connected to the AC2889)

**Comment by Obicom** [comment]
I connected the AC2889/10 with my Wifi successfully. Then I tried to add the integration with the IP address. After some seconds I got always "Timeout, cannot connect to device".  After  a restart of HA the AV2889 was automatedly discovered. After pressing "Configure" I got this error in the logs:

![image](https://github.com/kongo09/philips-airpurifier-coap/assets/25134482/06460770-551f-45d5-ad3f-a15bda34f12f)

After  Any hint or idea?

**Comment by mitompl** [comment]
same issue here, durring connection I get timeout..

**Comment by kongo09** [comment]
Is this a new or an old model? Old models might not support encrypted CoAP and this integration will not work. You might be lucky with an alternative integration.

This might be the connectivity problem of Philips, in which case you're out of luck. Did you try to connect to the device from the command line as described in the README?

**Comment by nashnix** [comment]
Same issue here, but with an AC1715/70.

I tried following the directions for the command line; it does not capture any events in the log. The Philips app is able to communicate and issue commands to the purifier with no problem though, and it responds to pings and is identified by other devices on the network.

The only thing captured at all was the failure to communicate with the 1715;

> 2023-08-10 20:28:51.430 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Timeout, host XXX.XXX.XXX.XXX doesn't answer, aborting
> 2023-08-10 20:29:29.610 ERROR (MainThread) [coap] Connection loss was not expected.

I'll have another go at this tomorrow and see if I can capture more information.

(edit: I should note that the exact same errors and no response have come from an AC2939/70, but that one is cooperating via homebridge so I'm not bothered by that)

**Comment by kongo09** [comment]
If you don't get a reply on the command line, I fear that nothing can be done. Your device might not be compatible with encrypted CoAP. The Phillips app communicates with a different mechanism using the cloud. Unfortunately, Phillips is not sharing the details about that API, although IFTTT has managed to get access somehow.

**Comment by nashnix** [comment]
I suspect that this is a case of "problem lies between keyboard and chair" - I don't think I executed the commands to make it write its findings to the logs properly.

I also wasn't clear that the failure in my comment above is from the GUI attempt, not the command line; it recorded the same response from the AC2939 via the GUI too, but that device is working very happily with a homebridge module. Will report back later and let you know if I manage to beat it into cooperating (or not).

---

Edit; it's definitely me not executing the CLI commands properly. Might be because it's running in a docker container.

---

Second edit; happy to report that I now have the logs; it was definitely my inability to talk to the CLI - I ended up using the homebridge module to capture what is happening.

I've attached the log here - [1715-on-off-log.txt](https://github.com/kongo09/philips-airpurifier-coap/files/12317943/1715-on-off-log.txt) - that is just me turning it on and off, nothing else. My suspicion, based on what the author of the homebridge fork said, is that it's just a matter of matching parameter mappings, but I admit that I really don't know enough to be very useful.

Is this the sort of thing that you need? If so I can run it while I send all the other commands, and compare that with the one that is working.
